### ISSUE TITLE
Just Started Getting: Action failed with error Error: versionSpec parameter is required

### ISSUE THREAD

**Issue by nibanks** [microsoft/action-publish-symbols#27]
I just merged a PR into [microsoft/xdp-for-windows](https://github.com/microsoft/xdp-for-windows) and our GH Action is failing with:

```
Action failed with error Error: versionSpec parameter is required
```

https://github.com/microsoft/xdp-for-windows/runs/7263931145?check_suite_focus=true.

cc @mtfriesen

**Comment by tanmayghosh2507** [comment]
Hi @nibanks Could you please use the 2.16 version("microsoft/action-publish-symbols@v2.1.6") of the publish symbol task instead of "microsoft/action-publish-symbols@44254ea6d79c64929877999567402c99de97a62d". Refer usage here: https://github.com/tanmayghosh2507/GitHubPublicActiontest/blob/main/.github/workflows/dotnetcore.yml#L29
Please let me know if the issue persists.

**Comment by nibanks** [comment]
Just merged and it ran. Looks all good now. Thanks! BTW, any idea why dependabot didn't automatically update to the latest for your action?
